const countriesEN = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const countriesRU = [
  "Афганистан",
  "Албания",
  "Алжир",
  "Андорра",
  "Ангола",
  "Антигуа и Барбуда",
  "Аргентина",
  "Армения",
  "Австралия",
  "Австрия",
  "Азербайджан",
  "Багамы",
  "Бахрейн",
  "Бангладеш",
  "Барбадос",
  "Беларусь",
  "Бельгия",
  "Белиз",
  "Бенин",
  "Бутан",
  "Боливия",
  "Босния и Герцеговина",
  "Ботсвана",
  "Бразилия",
  "Бруней",
  "Болгария",
  "Буркина-Фасо",
  "Бурунди",
  "Кабо-Верде",
  "Камбоджа",
  "Камерун",
  "Канада",
  "Центральноафриканская Республика",
  "Чад",
  "Чили",
  "Китай",
  "Колумбия",
  "Коморы",
  "Конго",
  "Коста-Рика",
  "Хорватия",
  "Куба",
  "Кипр",
  "Чешская Республика",
  "Демократическая Республика Конго",
  "Дания",
  "Джибути",
  "Доминика",
  "Доминиканская Республика",
  "Эквадор",
  "Египет",
  "Сальвадор",
  "Экваториальная Гвинея",
  "Эритрея",
  "Эстония",
  "Эсватини",
  "Эфиопия",
  "Фиджи",
  "Финляндия",
  "Франция",
  "Габон",
  "Гамбия",
  "Грузия",
  "Германия",
  "Гана",
  "Греция",
  "Гренада",
  "Гренада",
  "Гвинея",
  "Гвинея-Бисау",
  "Гайана",
  "Гаити",
  "Гондурас",
  "Венгрия",
  "Исландия",
  "Индия",
  "Индонезия",
  "Иран",
  "Ирак",
  "Ирландия",
  "Израиль",
  "Италия",
  "Ямайка",
  "Япония",
  "Иордания",
  "Казахстан",
  "Кения",
  "Кирибати",
  "Корея, Северная",
  "Корея, Южная",
  "Кувейт",
  "Кыргызстан",
  "Лаос",
  "Латвия",
  "Ливан",
  "Лесото",
  "Либерия",
  "Ливия",
  "Лихтенштейн",
  "Литва",
  "Люксембург",
  "Мадагаскар",
  "Малави",
  "Малайзия",
  "Мальдивы",
  "Мали",
  "Мальта",
  "Маршалловы острова",
  "Мавритания",
  "Маврикий",
  "Мексика",
  "Маршалловы острова",
  "Молдавия",
  "Монако",
  "Монголия",
  "Черногория",
  "Мароко",
  "Мозамбик",
  "Мьянма",
  "Намибия",
  "Науру",
  "Непал",
  "Нидерланды",
  "Новая Зеландия",
  "Никарагуа",
  "Нигер",
  "Нигерия",
  "Северная Македония",
  "Норвегия",
  "Оман",
  "Пакистан",
  "Палау",
  "Палестина",
  "Панама",
  "Папуа — Новая Гвинея",
  "Парагвай",
  "Перу",
  "Филиппины",
  "Польша",
  "Португалия",
  "Катар",
  "Румыния",
  "Россия",
  "Руанда",
  "Сент-Китс и Невис",
  "Сент-Люсия",
  "Сент-Винсент и Гренадины",
  "Самоа",
  "Сан-Марино",
  "Сан-Томе и Принсипи",
  " saudi arabia",
  "Сенегал",
  "Сербия",
  "Сейшелы",
  "Сьерра-Леоне",
  "Сингапур",
  "Словакия",
  "Словения",
  "Соломоновы Острова",
  "Сомали",
  "Южноафриканская Республика",
  "Испания",
  "Шри-Ланка",
  "Судан",
  "Суринам",
  "Швеция",
  "Швейцария",
  "Сирия",
  "Таджикистан",
  "Танзания",
  "Таиланд",
  "Тимор-Лесте",
  "Того",
  "Тонга",
  "Тринидад и Тобаго",
  "Тунис",
  "Турция",
  "Туркменистан",
  "Тувалу",
  "Уганда",
  "Украина",
  "Объединенные Арабские Эмираты",
  "Великобритания",
  "Соединенные Штаты",
  "Уругвай",
  "Узбекистан",
  "Вануату",
  "Ватикан",
  "Венесуэла",
  "Вьетнам",
  "Йемен",
  "Замбия",
  "Зимбабве",
];

export { countriesEN, countriesRU };
